### ISSUE TITLE
No need to re-fetch User from DB

### ISSUE THREAD

**Issue by PovilasKorop** [erengaygusuz/grade-calculator-web#1]
This line: https://github.com/erengaygusuz/grade-calculator-web/blob/071a010b719a017c4c87fbf9c2585086f9112b9a/app/Http/Controllers/HomeController.php#L29

```
public function index()
{
    $user = User::where('id', Auth::user()->id)->first();

    if ($user->option != NULL)
    {
        return redirect('/option/'.$user->option->id);
    }

    return view('home');
}
```

Two things here:

1. You don't need to take the user from the DB, it's automatically available as full User model object, with `Auth::user()` or `auth()->user()`
2. `$user->option` is a relationship but all you use is the ID field of this, so it is available in `Auth::user()->option_id`

So my version of this method would be:

```
public function index()
{
    if (auth()->user()->option_id) {
        return redirect('/option/'.auth()->user()->option_id);
    }

    return view('home');
}
```

**Comment by erengaygusuz** [comment]
You are right. I actually have user info but again I try to retrieve it. This is a bad mistake. I will fix it. Thanks.
