### ISSUE TITLE
Don't Check if User Exists

### ISSUE THREAD

**Issue by PovilasKorop** [erengaygusuz/grade-calculator-web#10]
This line: https://github.com/erengaygusuz/grade-calculator-web/blob/b17976740f3e812abb6b63adc84593ed1c54be6a/app/Http/Controllers/OptionController.php#L125

```
$user = User::where('id', Auth::user()->id)->first();

if ($user != NULL)
{
    return redirect('/option/' . $user->option->id);
}
```

Two things here:

1. As mentioned in another issue, logged-in user object is already in memory, with `Auth::user()`, what you need is `return redirect('option' . Auth::user()->option_id) }` because in what case User would NOT exist? Or, if you mean that system should check if the user is logged in, it's done with middleware `auth`.
2. This Controller has if condition and return. What does the Controller return in "else" condition? Nothing? I think that if-statement (repeating in other methods) is pointless.

**Comment by erengaygusuz** [comment]
Yes, I saw it yesterday. I will check every condition like that. Thanks for warning me.
