### ISSUE TITLE
Use Route Model Binding

### ISSUE THREAD

**Issue by PovilasKorop** [erengaygusuz/grade-calculator-web#3]
This line: https://github.com/erengaygusuz/grade-calculator-web/blob/071a010b719a017c4c87fbf9c2585086f9112b9a/app/Http/Controllers/OptionController.php#L17

```
public function getLevelsAndItsDatas($option_id)
{
    $levels = Option::where('id', $option_id)->first()->levels;
```

You can make it more simple, without specifying the query, using [Route Model Binding](https://laravel.com/docs/10.x/routing#route-model-binding):

```
use App\Models\Option;

public function getLevelsAndItsDatas(Option $option)
{
    $levels = $option->levels;
```

Then, in the routes:

```
Route::get('option/{option}', [App\Http\Controllers\OptionController::class, 'getLevelsAndItsDatas']);
```

**Comment by erengaygusuz** [comment]
Thanks. I will use this way.
